# Site Settings
title: Ester Riccardi
tagline: PhD Student in Computational Neuroscience at CIMeC (UniTN)
baseurl: ""
url: "http://e-ricc.github.io"

github_username:  e-ricc
# Build Settings
sass:
  sass_dir: _sass
  style: compressed

author:
  name: Ester Riccardi
  url: http://e-ricc.github.io
  email: ester.riccardi@unitn.it

# include: ['_pages']
kramdown:
  input: GFM