title: Ester Riccardi
tagline: PhD Student in Computational Neuroscience
url: http://e-ricc.github.io
baseurl: ""
# gems: [jekyll-paginate]
# paginate: 5

# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink: "/:title"
# relative_permalinks: true

sass:
  sass_dir: _sass
  style: compressed

author:
  name: Ester Riccardi
  url: http://e-ricc.github.io
  email: ester.riccardi@unitn.it

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'syntax'

excerpt_separator: <!--more-->

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from