# Site Settings
title: Ester Riccardi
email: ester.riccardi@unitn.it
description: >
  Ester Riccardi is a PhD student in Computational Neuroscience at CIMeC (UniTN)
baseurl: "/startjekyll"
url: "http://e-ricc.github.io"
github_username:  e-ricc
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM